host-tz-database: Fix build on Darwin
This patch fixes following build error:

    localtime.c:1174: error: static declaration of 'tzsetwall' follows non-static declaration
    /usr/include/time.h:150: error: previous declaration of 'tzsetwall' was here

On Linux:

    % grep -r tzsetwall /usr/include/
    [nothing]

On Mac OS 10.7:

    % grep -r tzsetwall /usr/include/
    /usr/include/time.h:void tzsetwall(void);

So this patch doesn't break Linux.

Signed-off-by: Bernhard Walle <bernhard@bwalle.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>