python3-ipython: add 4.1.1
We have to install *.py instead of *.pyc in this package because of this
traceback:

  Traceback (most recent call last):
    File "/usr/bin/ipython3", line 5, in <module>
      start_ipython()
    File "/usr/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    File "/usr/lib/python3.5/site-packages/traitlets/config/application.py", line 587, in launch_instance
    File "/usr/lib/python3.5/site-packages/traitlets/config/configurable.py", line 404, in instance
    File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 910, in __new__
    File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 934, in setup_instance
    File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 925, in setup_instance
    File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 2095, in instance_init
    File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 1563, in instance_init
    File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 492, in instance_init
    File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 483, in _dynamic_default_callable
    File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 109, in _deprecated_method
    File "/usr/lib/python3.5/inspect.py", line 930, in getsourcelines
    File "/usr/lib/python3.5/inspect.py", line 761, in findsource
  OSError: could not get source code

Signed-off-by: Florian Scherf <f.scherf@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>