ppp: fix building
Without this, building fails because the include paths to sysroot are
missing:

options.c:59:18: fatal error: pcap.h: No such file or directory
compilation terminated.
make[2]: *** [options.o] Error 1

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>