calibrator: set LDLIBS=-m instead of LDFLAGS=-m
Otherwise building may fail with:

arm-1136jfs-linux-gnueabi-gcc   -lm  calibrator.c   -o calibrator
/tmp/ccF52ORo.o: In function `analyzeCache':
calibrator.c:(.text+0x2398): undefined reference to `log10'
calibrator.c:(.text+0x23d0): undefined reference to `log10'

For newer compilers (e.g. gcc-4.7) the libs must be specified after
source/object files.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>