logrotate: Create directory for state file
When upgrading from logrotate 3.8.7 to 3.9.1 a new patch
patches/logrotate-3.9.1/0001-deb-config-h.patch was introduced which
changed the paths to DEFAULT_MAIL_COMMAND and STATEFILE. The statefile
was created by logrotate in /var/lib before, now it expects
/var/lib/logrotate to be present. If the directory is missing, logrotate
fails with the following error:

    error: error creating state file /var/lib/logrotate/status: No such file or directory

So after upgrading to ptxdist 2015.07.0 (containing the above mentioned
upgrade) all calls to logrotate must have been failed. This can easily
be fixed by just creating the empty folder.

Note: users may have overridden the path to the state file by passing
another path together with the -s option of logrotate.

Fixes: 878707bd943a04fc8e3a55a151499359e81ce780
Signed-off-by: Alexander Dahl <ada@thorsis.com>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>