host-mtd-utils: Fix build with gcc 5.1
The build of host-mtd-utils fails with link errors:

| ..../mkfs.ubifs/hashtable/hashtable_itr.o:
|         In function `hashtable_iterator_key':
| ..../mkfs.ubifs/hashtable/hashtable_itr.c:43:
|         multiple definition of `hashtable_iterator_key'
| ..../mkfs.ubifs/devtable.o:.../mkfs.ubifs/hashtable/hashtable_itr.h:34:
|         first defined here
| ..../mkfs.ubifs/hashtable/hashtable_itr.o:
|         In function `hashtable_iterator_key':
| ..../mkfs.ubifs/hashtable/hashtable_itr.c:43:
|         multiple definition of `hashtable_iterator_value'
| ..../mkfs.ubifs/devtable.o:..../mkfs.ubifs/devtable.c:64:
|         first defined here

The problem is the change of the default C standard from gnu89 to gnu11
which changes the semantics of 'inline'. The issue is described in the
Porting guide at https://gcc.gnu.org/gcc-5/porting_to.html. Adding the
'-fgnu89-inline' option fixes the issue.

Signed-off-by: Bernhard Walle <bernhard@bwalle.de>
[mol: use HOST_MTD_UTILS_CFLAGS  to add -fgnu89-inline]
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>