templates/kernel.make: don't try to strip non-executables
The current targetinstall in the template can fail when a new kernel
package is targetinstall'd:

  arm-v7a-linux-gnueabihf-strip:platform-v7a/packages/linux-4.9.30/lib/modules/4.9.30/modules.symbols.bin:
    File format not recognized
  Error: install_file failed!

This happens because the old rule passes the 'k' parameter to
install_copy for every file found in the .../linux-4.9.30/lib, which
effectively tries to also strip non-ELF files in that directory, like
the mentioned modules.symbols.bin.

The new implementation (copied from /rules/kernel.make) only passes the
'k' parameter for *.ko files in the lib folder, which causes only those
files to be stripped. The second install_glob rule then installs all remaining
files without stripping them.

Signed-off-by: Roland Hieber <r.hieber@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>