kernel: build perf without -Werror
"-C" breaks building with some toolchains. Building can  fail with:

[...]/usr/include/bits/mathinline.h: In function 'floor':
[...]/usr/include/bits/mathinline.h:746:380: error: expected ':' or ')' before string constant
[...]

Instead disable -Werror to avoid build errors caused by icecc and
-Wimplicit-fallthrough.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>