optee-client: fix building with gcc-7.x and icecc
Icecc splits preprocessing and compiling. As a result comments are no
longer available at compile time and building fails with:

src/rpmb.c: In function 'rpmb_data_req':
src/rpmb.c:675:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
src/rpmb.c:681:2: note: here

Compile with '-C' to preserve comments. This can have side effects, so it
cannot be enabled globally.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>