ptxd_make_world_compile.sh: conditionally redirect stderr>stdout
I discovered after updating to a new version of ptxdist that all of my
compile output including errors/warnings are now all going to stdout
instead of having the errors/warning going to stderr.

This is causing some problem when I use qtcreator as my IDE because
qtcreator will only filter stderr for errors/warnings to put into the
Issues tab, where one can simply click on the error/warning and be taken
right to the source line where the error/warning is found.

I found that this problem was introduced by commit
30b9267e35eea1c2edb4da0231a428bfa25b6766

This patch will conditionally redirect stderr>stdout on compile output
if ptxdist has output synchronization enabled.

This small program demonstrates the behavior with this patch applied:

$ cat local_src/testprog/testprog.c

int main(int argc, char *argv[])
{
        printf("Hello World, I'm testprog!\n");

        exit(EXIT_SUCCESS);
}

$ ptxdist compile testprog >/dev/null
testprog.c:4:2: error: #error An error here
 #error An error here
  ^
make[1]: *** [testprog] Error 1
make: *** [/home/jringle-admin/code/gpec/ec1k-rootfs/platform-EC1K/state/testprog.compile] Error 2

$ ptxdist compile --output-sync testprog >/dev/null
make: *** [/home/jringle-admin/code/gpec/ec1k-rootfs/platform-EC1K/state/testprog.compile] Error 2

$ ptxdist compile --no-output-sync testprog >/dev/null
testprog.c:4:2: error: #error An error here
 #error An error here
  ^
make[1]: *** [testprog] Error 1
make: *** [/home/jringle-admin/code/gpec/ec1k-rootfs/platform-EC1K/state/testprog.compile] Error 2

Signed-off-by: Jon Ringle <jringle@gridpoint.com>
[mol: bailout to PTXDIST_FD_STDERR and more cleanup]
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>