dnsmasq: fix inverse logic for lua activation
Since dnsmasq was updated in 1967b3f3b441e5f05e52fd75e900b9a13c4b5492,
it doesn't build any more:

make[2]: Entering directory '.../platform-arm-hf/build-target/dnsmasq-2.70/src'
arm-v7a-linux-gnueabihf-gcc -Wall -W -O2 -DHAVE_LUASCRIPT  -DVERSION='"2.70"' -c helper.c
helper.c:38:19: fatal error: lua.h: No such file or directory
 #include <lua.h>
                   ^
compilation terminated.

The logic of the lua activation flag was inverted: instead of activating
-DHAVE_LUASCRIPT if PTXCONF_DNSMASQ_SCRIPT_LUA was set, it was vice versa.

Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>