libelf: fix building with gcc-7.x and icecc
Icecc splits preprocessing and compiling. As a result comments are no
longer available at compile time and building fails with:

elf_cntl.c: In function 'elf_cntl':
elf_cntl.c:59:10: error: this statement may fall through [-Werror=implicit-fallthrough=]

Compile with '-C' to preserve comments. This can have side effects, so it
cannot be enabled globally.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>