host-localedef: Fix build with gcc 5.1
The build of host-localedef fails with lots of argp-related link errors:

| argp-help.o: In function `indent_to':
| argp-help.c:(.text+0x1335): undefined reference to `argp_fmtstream_point'
| argp-help.c:(.text+0x1352): undefined reference to `argp_fmtstream_putc'
| argp-help.o: In function `space':
| argp-help.c:(.text+0x137d): undefined reference to `argp_fmtstream_point'
| argp-help.c:(.text+0x13a5): undefined reference to `argp_fmtstream_putc'
| argp-help.c:(.text+0x13b8): undefined reference to `argp_fmtstream_putc'
| argp-help.o: In function `print_header':
| argp-help.c:(.text+0x1549): undefined reference to `argp_fmtstream_putc'
| argp-help.c:(.text+0x157f): undefined reference to `argp_fmtstream_set_lmargin'
| argp-help.c:(.text+0x159b): undefined reference to `argp_fmtstream_set_wmargin'
| argp-help.c:(.text+0x15b2): undefined reference to `argp_fmtstream_puts'
| argp-help.c:(.text+0x15c7): undefined reference to `argp_fmtstream_set_lmargin'
| argp-help.c:(.text+0x15dc): undefined reference to `argp_fmtstream_putc'
| argp-help.o: In function `comma':
| argp-help.c:(.text+0x167f): undefined reference to `argp_fmtstream_putc'
| argp-help.c:(.text+0x171e): undefined reference to `argp_fmtstream_set_wmargin'
| [...]

The problem is the change of the default C standard from gnu89 to gnu11
which changes the semantics of 'inline'. The issue is described in the
Porting guide at https://gcc.gnu.org/gcc-5/porting_to.html. Adding the
'-fgnu89-inline' option fixes the issue.

Signed-off-by: Bernhard Walle <bernhard@bwalle.de>
[mol: use HOST_LOCALEDEF_CFLAGS  to add -fgnu89-inline]
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>