ptxd_colgen_generate_sections: handle host and cross packages
Otherwise they won't be added to PTX_PACKAGES_SELECTED. This breaks
source -> packages mapping and causes the get stage to fail with:

error: empty parameter to 'ptxd_make_get'

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>