kernel: fix building perf with gcc-7.x and icecc
Icecc splits preprocessing and compiling. As a result comments are no
longer available at compile time and building fails with:

parse-options.c: In function 'get_value':
parse-options.c:101:7: error: this statement may fall through [-Werror=implicit-fallthrough=]
parse-options.c:104:3: note: here
parse-options.c: In function 'print_option_help':
parse-options.c:716:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
parse-options.c:719:2: note: here

Compile with '-C' to preserve comments. This can have side effects, so it
cannot be enabled globally.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>