dtc: Do not inhibit linemarker generation if supported
Without linemarkers the error messages are somehwat useless.
To demonstrate I picked a random .dts file file from the arm tree in
linux sources:
DTC ptx-testprj_arm/platform/images/vf610-twr.dtb
Error: /tmp/testprj/platform/state/vf610-twr.dts.tmp:366.1-5 syntax error
FATAL ERROR: Unable to parse input tree

If linemarkers are inserted the error message clearly states in which file
which line caused the error:

DTC ptx-testprj_arm/platform/images/vf610-twr.dtb
Error: /tmp/testprj/platform/build-target/linux/arch/arm/boot/dts/vf610-twr.dts:13.1-5 syntax error
FATAL ERROR: Unable to parse input tree

The support for #line markers was added in the same release as -i was
added. So add -P only if -i is not supported.

Signed-off-by: Alexander Stein <alexander.stein@systec-electronic.com>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>