dconf: move to staging
Building with dbus 1.12.2 fails with:

[...]/sysroot-target/usr/include/dbus-1.0/dbus/dbus-address.h:74:15: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
 static inline void

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>