* wget: bug variable name in wget.make; patch by Erwin Rol.
	When compiling wget it breaks with the following error message:

	--------------------
	target: wget.extract
	--------------------

	extract: archive=/home/erwin/Download/ptxdist_cache//wget-1.9.1.tar.gz
	extract: dest=/data/Clients/Annax/Projects/InfoSys/ptxdist/projects/ETH2/platform-ETH2/build-target

	Error: empty parameter to "patchin()"

	make: *** [/data/Clients/Annax/Projects/InfoSys/ptxdist/projects/ETH2/platform-ETH2/state/wget.extract] Error 1

	This patch renames the variable from WGET to WGET_PACKET, But this can't
	be the right solution. Some things like extract seem to need WGET and
	things like patching need WGET_PACKET. So this is more a bug report than
	a patch.


git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@8710 33e552b5-05e3-0310-8538-816dae2090ed