host-qt4: Enable openssl
The build breaks if with a bunch of QSslSocket errors such as:

undefined reference to `QSslSocket::staticMetaObject'

Signed-off-by: Jon Ringle <jringle@gridpoint.com>