ipkg-utils: fix UID-related problem with ar
I had a strange problem when I tried to create an image.
The last part of the error message was:

File
"<path to ptxdist>/projects/<project name>/ \
platform-<project name>/sysroot-host/lib/python2.6/site-packages/arfile.py",
line 79, in _scan
    size = int(descriptor[5])
ValueError: invalid literal for int() with base 10: '`'

The problem eventually turned out to be that arfile.py has trouble parsing AR
files created with a UID >99999 - it relies on the (ascii) AR header fields
using one digit less than their allocated sizes so it can the padding
space to split() them.

There is no real need to use the actual UID in the ar header, and GNU AR has a
'D' option that uses UID and GID values of zero when creating the ipkg archive.
I have put together a quick patch that tells ptxdist to patch ipkg-build to use
the 'D' option when invoking AR.

Signed-off-by: Darren Hutchinson <dhutchinson@google.com>
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>