host-mtd-utils: add missing dependency to ACL
Without this dependency it fails to build with:

mkfs.jffs2.c:70:21: fatal error: sys/acl.h: No such file or directory
#include <sys/acl.h>
                    ^
compilation terminated.

Signed-off-by: Juergen Borleis <jbe@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>